### ISSUE TITLE
List-KR DNS blocklists

### ISSUE THREAD

**Issue by piquark6046** [mullvad/dns-blocklists#104]
Project URL: https://github.com/List-KR/List-KR
Subscription URL of the DNS blocklist: https://cdn.jsdelivr.net/gh/adguardteam/HostlistsRegistry@main/assets/filter_25.txt

**Comment by jbjorkang** [comment]
Why should we add this?

**Comment by piquark6046** [comment]
To block advertisement on websites of South Korea.

**Comment by jbjorkang** [comment]
Thanks. We will review and consider this internally
