### ISSUE TITLE
[request] Make the social blocklist available as an IP that can be entered in the Mullvad app for DNS blocking

### ISSUE THREAD

**Issue by rowboatz** [mullvad/dns-blocklists#106]
Currently, the 'Social media' blocklist cannot be used through the Mullvad app, not as a filter toggle nor as an IP that can be set as a custom DNS server. I would find it very useful to be able to use this list directly through the Mullvad app. Would it be possible to add some blocking combination IPs that include that blocklist in the list [here](https://github.com/mullvad/dns-blocklists#custom-dns-entries-for-use-with-our-vpn-service)?

**Comment by vistor-m** [comment]
Hello, we are are aware of this and it's on our todo to implement asap.
