### ISSUE TITLE
Tracker suggestion

### ISSUE THREAD

**Issue by Minalinsky007** [mullvad/dns-blocklists#107]
Please use exodus privacy database, would be very usefull for android users
https://reports.exodus-privacy.eu.org/en/trackers/

**Comment by jbjorkang** [comment]
Thanks for reaching out. Do they happen to have an open source list of URLs that we can use?

**Comment by Minalinsky007** [comment]
> Thanks for reaching out. Do they happen to have an open source list of URLs that we can use?

Hi, I'm not tech heavy man, but maybe you can find it on their github page 
https://github.com/Exodus-Privacy

**Comment by jbjorkang** [comment]
Thanks. For now we will make a note and investigate in the future.
