### ISSUE TITLE
Include Hagezi’s lists

### ISSUE THREAD

**Issue by KobyKola** [mullvad/dns-blocklists#108]
It’s already been mentioned to use Hagezi’s list but missunderstood that they are all combined into one. Hagezi’s offers multiple lists that are all separated.

advertising (blocks a similar amount of trackers as adguarddns list which is already in Mullvad advertising): multi light, or multi normal, or multi pro

malware: Threat intelligence feeds, Most abused TLDS, Fake

Native: Native trackers

Gambling: gambling filter

The benefit of using Hagezi is it includes adguarddns, oisd and a HUGE amount of other lists (https://github.com/hagezi/dns-blocklists/blob/main/sources.md) while removing almost all false positives like oisd.

Which is why many other services like Ivpn, next dns, adguard dns, RethinkDns, and controlD already include it or offer it as an option.

**Comment by ShailendraMadarie** [comment]
Yes, i agree.
Hope to see hagezi list soon on mullvad

**Comment by Entertainment91** [comment]
> Yes, i agree. Hope to see hagezi list soon on mullvad

Same here. Tried Hagezi's list the last few weeks via personalDNS and have to admit that the protection is noticeably better than Mullvald's previous ones...

**Comment by jbjorkang** [comment]
Thanks for this feedback. For the time being I cannot foresee us adding this list, but that may change in the future.
