### ISSUE TITLE
Dnscrypt support

### ISSUE THREAD

**Issue by sivajipro** [mullvad/dns-blocklists#109]
Any plan to support [DNSCrypt](https://github.com/DNSCrypt) ?

**Comment by jbjorkang** [comment]
We have no plans currently. What are you looking for?

**Comment by sivajipro** [comment]
Well dnscrypt have better privacy and faster than doh.

**Comment by jbjorkang** [comment]
Okay. We currently have no plans to migrate from what we using.

If you have concrete suggestions, references and implementation details, I would welcome it. However, saying that DNScrypt has better privacy without nothing to back it up, is not a valid enough reason to have us work on switching or adding support.
