### ISSUE TITLE
base.dns.mullvad.net not working as expected since recent changes

### ISSUE THREAD

**Issue by iyanmv** [mullvad/dns-blocklists#114]
Hi,

Since a few days ago, `base.dns.mullvad.net` is not working as before, letting passed many more ads than it used to. Two sites where I noticed a huge increase are: https://elpais.com/ and https://www.marca.com/. Using Pi-hole in addition to this DNS helps. But this is not an option when outside my wifi, where I used to simply set `base.dns.mullvad.net` as Private DNS option on Android, and that would be enough.

Anything I can do from my part to identify the commit that caused the issue?
Thanks

**Comment by jbjorkang** [comment]
Thanks for this, we will investigate.

**Comment by jbjorkang** [comment]
We believe this issue has been resolved. Please contact us again if you experience the same problems.

**Comment by iyanmv** [comment]
Yes, it appears to have been solved. Thanks!
