### ISSUE TITLE
Add Reddit and LinkedIn to Social Block list

### ISSUE THREAD

**Issue by christophjanke** [mullvad/dns-blocklists#119]
Hey everyone,

first time opening a Github issue - please let me know if I am doing something wrong.

I would like to suggest adding Reddit and LinkedIn to the social blocklist. Both are currently only mentioned in files/social as redditpic.twitter.com and linkedinpic.twitter.com.

As they are social media networks with a significant usage size, especially in the tech savvy user group that tends to use these features of mullvad, I think it would be appropriate to add these to the file.

Thanks for consideration!

**Comment by jbjorkang** [comment]
Thanks for this suggestion. I will take this internally and we will consider it!
