### ISSUE TITLE
Consider switching gambling block list provider due to inactivity

### ISSUE THREAD

**Issue by sneezingabbey** [mullvad/dns-blocklists#120]
Hello,

It has been approximately 3 months since I initially created the add request/github issue concerning CSGO and Rust gambling websites on [Blocklist Project](https://github.com/blocklistproject/Lists) with Issue #1068 ([Link](https://github.com/blocklistproject/Lists/issues/1068)). Upon further examination of their issue tracker, I noticed that the last time they closed an issue was around 4 months and 17 days ago, as of the date of this writing.

I believe it might worth it, to switch to a more up-to-date gambling list provider for Mullvad. Let me know what you think.

**Comment by jbjorkang** [comment]
Thanks for this feedback. We will investigate.

**Comment by hagezi** [comment]
@jbjorkang https://github.com/hagezi/dns-blocklists#gambling

**Comment by jbjorkang** [comment]
> @jbjorkang https://github.com/hagezi/dns-blocklists#gambling

@hagezi https://github.com/mullvad/dns-blocklists/commit/233f128ed35bafe50ae205dc3757d3fc00893ad4
