### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by shuvashish76** [mullvad/dns-blocklists#121]
Hello, what is the license of this project?

**Comment by jbjorkang** [comment]
I will need to research what the best approach is here. For now it is down to what each list upstream has.

**Comment by shuvashish76** [comment]
I think some creative commons license would be perfect ?
[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)

**Comment by hagezi** [comment]
I don't understand why you should license simple lists of existing domains. What is being licensed?

**Comment by shuvashish76** [comment]
Everything should be properly licensed even if they're art-work, blog posts or _simple domains lists_.
In this case its a list of collection handpicked by mullvad hence I suggested for creative commons license. Usually no license means "proprietary" by default.

**Comment by AttractLight** [comment]
I don't think mere lists can be copyrighted. But in this repository, it contains some scripts so CC0 would be good for such a very small project. Nobody cares the copyright of small codes after all.

**Comment by shuvashish76** [comment]
> We have talked about this for a bit internally, but we need to investigate this further.

@Soren90 Any conclusion?
