### ISSUE TITLE
Block OneTrust Privacy Annoyances

### ISSUE THREAD

**Issue by riei2922jww** [mullvad/dns-blocklists#127]
### Have you contacted the Support Team already?

- [X] I have attempted already, but to no avail, or they pointed me here.

### What are the issues you need support with?

Please add:
my.onetrust.com
geolocation.onetrust.com
mobile-data.onetrust.io

To the blocklist to prevent these annoying cookie pop-ups on 70% of applications.

![IMG_8877](https://github.com/mullvad/dns-blocklists/assets/154846714/e289e217-1362-4c44-9053-7a61b1b9f39d)

**Comment by jbjorkang** [comment]
Do you know of any block lists that already include this? My fear is that just add these without knowing the side-effects.
