### ISSUE TITLE
Please add 1Hosts (Lite)

### ISSUE THREAD

**Issue by Cometin2002** [mullvad/dns-blocklists#129]
### Have you contacted the Support Team already?

- [X] I have attempted already, but to no avail, or they pointed me here.

### What are the issues you need support with?

Consider adding the list 1Hosts (Lite) 
https://o0.pages.dev/

**Comment by jbjorkang** [comment]
What reasons are there for adding that list in addition to the ones we have? Are there URLs not blocked with the methods we have?

**Comment by Cometin2002** [comment]
I can ask for support, but since I asked for it here and the reasons is to make the advertising block more robust without breaking anything
