### ISSUE TITLE
Apple apps all images are being blocked

### ISSUE THREAD

**Issue by wesley-maney** [mullvad/dns-blocklists#130]
### Tried reporting upstream already?

- [X] I have attempted already, but to no avail.

### What are the desired URLs to be unblocked?

I’m not entirely sure which filter is the culprit.

### Additional Information

First of all apologies if this is the wrong place or if you needed more details.

When using Apple Music or the iOS App Store it doesn’t render any images (no album art, banner art, no app icons and no app screenshots).

Apparently ProtonVPN also had this issue but fixed it a few days ago.

It seems to be caused by the ad-blocking part of Mullvad DNS (I’m using the “base” filter myself).

For more context here’s also a Reddit post about it (not mine): https://www.reddit.com/r/mullvadvpn/comments/1akvwx2/is_there_any_way_to_fix_this_issue_in_apple_apps/

screenshots:
![IMG_8394](https://github.com/mullvad/dns-blocklists/assets/13488705/293ea2b1-cb58-42fb-a3ca-8e30d8d66c5a)
![IMG_8395](https://github.com/mullvad/dns-blocklists/assets/13488705/1112392d-befa-49d4-be88-d5bd99ddcc8c)

**Comment by jbjorkang** [comment]
The most recent commit that I pushed today should resolve this. You'll see this within 24 hours from our VPN servers.

**Comment by user733626** [comment]
it seems to be working now again, thanks!
