### ISSUE TITLE
Add hagezi's Threat Intelligence Feeds for malware blocking

### ISSUE THREAD

**Issue by Dispatch3376** [mullvad/dns-blocklists#134]
### Have you contacted the Support Team already?

- [X] I have attempted already, but to no avail, or they pointed me here.

### What are the issues you need support with?

"A blocklist for blocking malware, cryptojacking, scam, spam and phishing. Blocks domains known to spread malware, launch phishing attacks and host command-and-control servers."

https://github.com/hagezi/dns-blocklists?tab=readme-ov-file#tif

**Comment by oskaralmlov** [comment]
@mullvad/infrastructure @Soren90 
Do we see any issues with adding this on top of the list we already have (urlhaus)?
Seems like a good addition.

**Comment by Soren90** [comment]
Hello,

I just want you guys to know that we have an internal issue for this. We are working on it and it will be added pretty soon.

**Comment by oskaralmlov** [comment]
After some testing we have now added the _mini_ variant of this list and the README has been updated to reflect this.

Thanks for submitting your request :)
