### ISSUE TITLE
bsky.app is not blocked

### ISSUE THREAD

**Issue by curlingchimpanzeeowl** [mullvad/dns-blocklists#137]
### Have you contacted the Support Team already?

- [X] I have attempted already, but to no avail, or they pointed me here.

### What are the issues you need support with?

bsky.app is a microblogging service.

**Comment by oskaralmlov** [comment]
Thank you. I have submitted a PR that adds this domain.

**Comment by Soren90** [comment]
Hello!

I've now added misskey.io to main. This will be pushed to our DNS servers soon.
