### ISSUE TITLE
misskey.io is not blocked

### ISSUE THREAD

**Issue by curlingchimpanzeeowl** [mullvad/dns-blocklists#138]
### Have you contacted the Support Team already?

- [X] I have attempted already, but to no avail, or they pointed me here.

### What are the issues you need support with?

Misskey.io is not blocked when social media lists are enabled.
misskey.io is a microblogging service.

**Comment by Soren90** [comment]
Hello!

I've now added misskey.io to main. This will be pushed to our DNS servers soon.
