### ISSUE TITLE
Add misskey-hub.net to Social block list

### ISSUE THREAD

**Issue by curlingchimpanzeeowl** [mullvad/dns-blocklists#140]
### Have you contacted the Support Team already?

- [X] I have attempted already, but to no avail, or they pointed me here.

### What are the issues you need support with?

Could you please add [misskey-hub.net](https://misskey-hub.net/en/) to Social block list?

**Comment by oskaralmlov** [comment]
Hi,

I looked at the website hosted @ misskey-hub.net and it appears to just be the website of the project and not a site that is actually hosting an actual social media platform. My verdict is that this should not be added to the list. 

If I'm incorrect about the site's purpose feel free re-open the issue.
