### ISSUE TITLE
pp39.cn is not blocked

### ISSUE THREAD

**Issue by pa0896** [mullvad/dns-blocklists#144]
### Have you contacted the Support Team already?

- [X] I have attempted already, but to no avail, or they pointed me here.

### What are the issues you need support with?

The website pp39.cn is an adult website which should be blocked by the adult content filters however it is accessible. Please add it to blocklist

**Comment by Soren90** [comment]
Hello @pa0896 

We are not maintaining the adult blocklist, we are getting it from: https://oisd.nl
If you find domains that are not included, please report it to the upstream list.

I've reported this domain to oisd now.
