### ISSUE TITLE
Blocklist for Smart-TVs

### ISSUE THREAD

**Issue by kresdjan** [mullvad/dns-blocklists#53]
I tried searching then EasyPrivacy list for some entries found in [Perflyst](https://github.com/Perflyst) / [PiHoleBlocklist](https://github.com/Perflyst/PiHoleBlocklist) / [SmartTV.txt](https://github.com/Perflyst/PiHoleBlocklist/blob/master/SmartTV.txt) but I was unsuccessful. So please considering adding a blocklist for smart-tvs and perhaps gaming consoles.

**Comment by jbjorkang** [comment]
Thanks for this. We can review it and consider adding such lists in coming months.

**Comment by Nickfost** [comment]
+1
