### ISSUE TITLE
Troubled Domains Permitted

### ISSUE THREAD

**Issue by Eow2022yia** [mullvad/dns-blocklists#54]
Hi,

mobile-data.onetrust.io is constantly creating pop-ups asking for non-essential data collection on multiple mobile apps, this domain has already been blocked on several pi-holes and other DNS resolvers like ControlD.

telemetry.bluedot.io is also permitted and profiling across multiple mobile applications.

Please can you strongly consider blocking these 2 domains?

Thanks.

**Comment by jbjorkang** [comment]
Thanks for your feedback. We are not planning to add individual domains for the time being. Is this domain found in any other list that we can investigate and maybe pull in?

**Comment by Eow2022yia** [comment]
> 

Hi, thank you for following up, yes.

These domains are blocked by the following pi-holes:

telemetry.bluedot.io is being blocked by Energized Ultimate, Energized Basic, 1Hosts (Pro) and 1Hosts (Xtra).

mobile-data.onetrust.io is being blocked by
Goodbye Ads, Energized Ultimate, 1Hosts (Lite), Energized Basic, 1Hosts (Pro), 1Hosts (mini) and 1Hosts (Xtra).

Pi-hole GitHub(s):
https://github.com/jerryn70/GoodbyeAds

https://github.com/EnergizedProtection/block

https://o0.pages.dev

Thank you.

**Comment by Eow2022yia** [comment]
> Thanks for your feedback. We are not planning to add individual domains for the time being. Is this domain found in any other list that we can investigate and maybe pull in?

Hi, thank you for following up, yes.

These domains are blocked by the following pi-holes:

telemetry.bluedot.io is being blocked by Energized Ultimate, Energized Basic, 1Hosts (Pro) and 1Hosts (Xtra).

mobile-data.onetrust.io is being blocked by
Goodbye Ads, Energized Ultimate, 1Hosts (Lite), Energized Basic, 1Hosts (Pro), 1Hosts (mini) and 1Hosts (Xtra).

Pi-hole GitHub(s):
https://github.com/jerryn70/GoodbyeAds

https://github.com/EnergizedProtection/block

https://o0.pages.dev

Thank you.
