### ISSUE TITLE
Typo in GitHub About description

### ISSUE THREAD

**Issue by titanism** [mullvad/dns-blocklists#58]
```diff
-Ad, tracker, adult content and gamlbing blocking for our DNS blocking service
+Ad, tracker, adult content, and gambling blocking for our DNS blocking service
```
<img width="311" alt="Screen Shot 2022-08-07 at 1 33 00 PM" src="https://user-images.githubusercontent.com/101466223/183305857-9be53e36-13fe-492c-9bcb-5ae170f027b7.png">

**Comment by jbjorkang** [comment]
Thanks!
