### ISSUE TITLE
Gambling and Adult content blocklists domains not getting blocked

### ISSUE THREAD

**Issue by iamagro** [mullvad/dns-blocklists#60]
If I try to go to any of the sites contained within those blocklists, the sites does not get blocked, is this normal?
Ads are getting blocked, DNS is set fine on my router, i'm getting 79% of ads and trackers blocked in [this test](https://d3ward.github.io/toolz/adblock.html).

**Comment by jbjorkang** [comment]
Could you give me a server or list of servers where you experience this? Thanks

**Comment by iamagro** [comment]
> Could you give me a server or list of servers where you experience this? Thanks

I tried some of the domains listed in [this](https://raw.githubusercontent.com/blocklistproject/Lists/master/alt-version/gambling-nl.txt) blocklist, almost all of them  worked (they shouldn't)

[bestbet.com](bestbet.com)
[88sports.com](88sports.com)
[368bet.com](368bet.com)
[betfair.com](betfair.com) (redirects to _"betfair.it/sport"_)
[bwin.com](bwin.com) (redirects to _"sports.bwin.it/it/sports"_)

These are only some of them, in reality the working domains are way more.

Same thing for all the Adult Content Blocklists.

**Comment by jbjorkang** [comment]
> > Could you give me a server or list of servers where you experience this? Thanks
> 
> I tried some of the domains listed in [this](https://raw.githubusercontent.com/blocklistproject/Lists/master/alt-version/gambling-nl.txt) blocklist, almost all of them  worked (they shouldn't)
> 
> [bestbet.com](https://bestbet.com)
> [88sports.com](https://88sports.com)
> [368bet.com](https://368bet.com)
> [betfair.com](https://betfair.com) (redirects to _"betfair.it/sport"_)
> [bwin.com](https://bwin.com) (redirects to _"sports.bwin.it/it/sports"_)
> 
> These are only some of them, in reality the working domains are way more.
> 
> Same thing for all the Adult Content Blocklists.

Could you give me some of the VPN servers you connected to when you experienced this? Were you using SOCKS5?

**Comment by iamagro** [comment]
My router automatically chose 149.112.112.112 as DNS Server (DoT)

I don't know what SOCKS5 is, but i see it's an alternative to a VPN, so i'm probably not using it, i'm not using any VPN service as well.

**Comment by jbjorkang** [comment]
> My router automatically chose 149.112.112.112 as DNS Server (DoT)
> 
> I don't know what SOCKS5 is, but i see it's an alternative to a VPN, so i'm probably not using it, i'm not using any VPN service as well.

Ah! Then I see the problem. The DNS over TLS service does not include anything but advert and tracker blocking currently.

I should update the README to clarify, sorry for the confusion!

You can import the lists in `output/relay` if you're using something like PiHole, this could be a stop gap solution at least.

Thanks for reaching out and adding this issue!
