### ISSUE TITLE
IPv6 for the DNS combinations

### ISSUE THREAD

**Issue by willmcginnis** [mullvad/dns-blocklists#64]
I just discovered this through privacyguides.org and I'm rolling it out to all of my devices and clients' devices! I think it would be good to also offer them over IPv6.

Mullvad does list an IPv6 DNS options on this page, but it might not be public:
https://mullvad.net/en/help/dns-over-https-and-dns-over-tls/

But even then the IPv6 only says it does adblock, rather than the other blocklists available here.

Just for setting up in routers it's great to have these IP options.

**Comment by jbjorkang** [comment]
Thanks for your feedback! We will keep this in mind for future!

**Comment by oskaralmlov** [comment]
We have decided to not offer **all** possible combinations as part of our public encrypted dns service. Instead we will be offering some commonly used combinations. We'll _soon_ be updating our guides to reflect these changes but you can start use them now if you want to. They all have A and AAAA records associated:

```
dns.mullvad.net
adblock.dns.mullvad.net        ads + trackers (they overlap so much they don't make sense as separate lists)
base.dns.mullvad.net              ads + trackers + malware
extended.dns.mullvad.net     ads + trackers + malware + social media
all.dns.mullvad.net                  ads + trackers + malware + social media + gambling + adult
