### ISSUE TITLE
[Question] How many time tose list are updated (as many as here or more) ?

### ISSUE THREAD

**Issue by ghost** [mullvad/dns-blocklists#66]
[Question] How many time tose list are updated (as many as here or more) ?

And if it's more often updated can you refresh them here too (too let us see witch actual version is used on the server.

Thanks !

**Comment by jbjorkang** [comment]
We update the lists every month where we can. Sometimes, like these last 2 months we have had other projects that have meant the refreshing of lists gets delayed.

We will update the lists you see in the canary branch to around 20 servers next week, the rest will happen likely the week after.
