### ISSUE TITLE
ipinfo.io wrongly in ads category

### ISSUE THREAD

**Issue by thansk** [mullvad/dns-blocklists#69]
ipinfo.io is at best tracking but definitely not ads

**Comment by hampuskraft** [comment]
The same goes for t.co, which also seems to be classified as ads, breaking all link presses on Twitter. I assume it should be fixed upstream in one of the [advertising blocklists](https://github.com/mullvad/dns-blocklists#advertising), though.

**Comment by taviowong** [comment]
> The same goes for t.co, which also seems to be classified as ads, breaking all link presses on Twitter. I assume it should be fixed upstream in one of the [advertising blocklists](https://github.com/mullvad/dns-blocklists#advertising), though.

The yoyo adblock list includes trackers as well. According to [their site](https://pgl.yoyo.org/adservers/news.php?#trackers-filtering), `?notrackers=1` should be added to the URL to exclude trackers from the list.

**Comment by jbjorkang** [comment]
Hopefully this is resolved now

**Comment by hampuskraft** [comment]
ipinfo.io and t.co are both still blocked on my end.
