### ISSUE TITLE
Adblocker as ublocker origin.

### ISSUE THREAD

**Issue by miltonjsvidal** [mullvad/dns-blocklists#70]
This dns block lists are flexible, because, in my Amazon app, Youtube app and in my browser (Samsung internet with Adguard as adblocker) They keep on ads and cosmetics ads appearing.  
![Screenshot_20221031-070255_Amazon Shopping](https://user-images.githubusercontent.com/72321331/198993692-56f7ac40-d00c-45d0-bb4e-6a7411bd8f3e.jpg)
![Screenshot_20221031-070214](https://user-images.githubusercontent.com/72321331/198993698-5aa2952c-1dba-40b4-b095-70f38e6344bb.jpg)

**Comment by jbjorkang** [comment]
I'm not sure what you want here?

**Comment by miltonjsvidal** [comment]
Mullval vpn needs improve adblocking

**Comment by jbjorkang** [comment]
> Mullval vpn needs improve adblocking

Okay. We refresh this monthly. This is not meant to be a replacement for other blocking solutions, but rather to complement them.

There are limitations on what can be blocked with DNS, however.

If you have specific lists that block more and are worthy of our trust, please share them.

**Comment by miltonjsvidal** [comment]
https://github.com/badmojr/1Hosts this is a good one

**Comment by abuturaaab** [comment]
Would great to add Hagezi lists, may be pro or normal list. They are updated quite regularly.

https://github.com/hagezi/dns-blocklists

**Comment by jbjorkang** [comment]
Thanks for the feedback here. I am closing this issue for the time being, but we might revisit the lists mentioned here in future.
