### ISSUE TITLE
Essential Missing Sites/Domains From Mullvad’s AdBlock DNS

### ISSUE THREAD

**Issue by Eow2022yia** [mullvad/dns-blocklists#73]
Hello there,

Please may I request a review for the following domains to be blacklisted as they are adware and/or trackers:

	1.	fengkongcloud.com
	2.	urbanairship.com
	3.	scorecardresearch.com
	4.	telemetry.bluedot.io
	5.	stocks-analytics-events.news.apple-dns.net
	6.	device-metrics-us-2.amazon.com
	7.	device-metrics-us.amazon.com
	8.	firebaseinstallations.googleapis.com
	9.	firebasedynamiclinks.googleapis.com
	10.	firebaseremoteconfig.googleapis.com
	11.	firebaseinappmessaging.googleapis.com
	12.	fcmtoken.googleapis.com
	13.	k.isprog.com 
	14.	deviceid.tantanapp.com
	15.	sc-report.tantanapp.com
	16.	devices.tantanapp.com
	17.	client-monitor.tantanapp.com
	18.	report.tantanapp.com
	19.	client-tracking.tantanapp.com
	20.	paas-push-api-log.immomo.com
	21.	referee.immomo.com
	22.	counter.tantanapp.com
	23.	connperf.immomo.com
	24.	app-log-lab.tantanapp.com
	25.	geolocation.onetrust.com
	26.	cdn.cookielaw.org
	27.	row-advil.waze.com
	28.	advil.waze.com
	29.	scontent-iad3-1.cdninstagram.com
	30.	scontent-iad3-2.cdninstagram.com
	31.	app-site-association.cdn-apple.com
	32.	paas-push-api.immomo.com
	33.	autoupdate.tantanapp.com
	34.	keepconn.tantanapp.com
	35.	keepconn.gcp.vip.tantanapp.com
	36.	app-site-association.cdn-apple.com
	37.	notice.sp-prod.net
	38.	campaign.adobe.com
	39.	datadoghq.eu
	40.	datadoghq.com
	41.	geolocation.onetrust.com
	42.	redirector.gvt1.com
	43.	analytics.google.com
	44.	redirector.googlevideo.com
	45.	reports.radiotime.com
	46.	protostats.bigo.sg
	47.	bugsnag.com
	48.	usabilla.com
	49.	analytics.sky.com
	50.	metrics.sky.com
	51.	smetrics.sky.com
	52.	madmetrics.com
	53.	dzc-metrics.mzstatic.com
	54.	braze.com
	55.	braze.eu
	56.	smetrics.mcdonalds.com
	57.	onetag.com
	58.	webproxy-advp.iad-apple.com.akadns.net
	59.	tracedock.com
	60.	ingenioustechnologies.com
	61.	a8.net
	62.	actionlink.jp
	63.	365you.com
	64.	securemvt.apple.com
	65.	userreport.com
	66.	sf16-muse-va.ibytedtos.com
	67.	startup.mobile.yandex.net
	68.	mc.yandex.ru
	69.	graph.digiseller.ru
	70.	postaffiliatepro.com
	71.	eulerian.net
	72.	bat.bing.com
	73.	quantummetric.com
	74.	lightboxcdn.com
	75.	quantummetric.com
	76.	ads.54646.co
	77.	adfarm.adition.com
	78.	benabid.me
	79.	cryft.com
	80.	adfarm1.adition.com
	81.	mobile-data.onetrust.io

     * Some may already be blocked.

Thank you.

**Comment by jbjorkang** [comment]
Thanks for your suggestion. Would you happen to know of a list that contains these that we can include?

**Comment by hagezi** [comment]
@jbjorkang 

You can use my [personal blocklist](https://github.com/hagezi/dns-blocklists#personal), it covers the domains except for domains that have nothing to do with ads and tracking or restrict functionality. Blocking the listed firebase domains for example will cause problems in several apps.
It may fit for one user, but not for the masses.

Alternatively you are welcome to use a version of my total blocklists, details about the blocklists and versions can be found at:
https://github.com/hagezi/dns-blocklists

Kind Regards,
Gerd

**Comment by Eow2022yia** [comment]
> Thanks for your suggestion. Would you happen to know of a list that contains these that we can include?

Hi,

This is from my own personal list of domains that are not released,

However many of these may also be found on 1HostsPro and Energized Protection Block Lists.

Thank you.
