### ISSUE TITLE
Add support for DNSCrypt

### ISSUE THREAD

**Issue by Sn0whax** [mullvad/dns-blocklists#75]
DNSCrypt offers several advantages over DOT and DOH. 

DOT has the following disadvantages when compared to DNSCrypt: 
- Provides more information than regular DNS to resolver operators in order to fingerprint clients, and this has (intentionally?) never been addressed in the specification
- Uses a dedicated port (853) likely to be blocked or monitored in situations where DNS encryption is useful
- Initial connection is slow due to the long handshake (until TLS 1.3 is deployed, which can take time due to [middleboxes](https://chefkochblog.wordpress.com/2017/12/20/tls-1-3-gets-blocked-by-cisco-avast-nsa/))
- Not well understood even by its proponents. It is a truck, as it is heavy and slow to load, but most if not all implementations perform a full round trip for every packet (even the excellent miekg/dns library as used by Tenta).
- Padding rules haven’t been specified besides a draft that doesn’t have any implementations, and a last-minute hack that requires altering DNS record sets before wrapping them
- Requires a full TLS stack, introducing a large attack surface
- Difficult to implement securely. Validating TLS certificates in non-browser software is [the most dangerous code in the world](https://crypto.stanford.edu/~dabo/pubs/abstracts/ssl-client-bugs.html)
-Readily compatible with industry-standard TLS interception/monitoring devices. Having people [install additional root certificates](https://sk.tl/3n7mJ9K4) is easier than custom software. Vendors are always ready to [passively extract information from TLS 1.3 sessions](https://sk.tl/7xmjiWwx).
- Requires TCP
- Requires sessions tracking on the server
- TLS is a generic transport mechanism. It doesn’t support reordering and parallelism and doesn’t include any ways to manage priorities. New mechanisms need to be invented and implemented to do so.
- Key management can be surprisingly hard especially if public key pinning is used by clients
- Allows insecure algorithms and parameters
- Will be difficult to improve without introducing more hacks. Unlikely to benefit from any improvements besides new TLS versions or homegrown reinventions.
- Questionable practical benefits over DoH

DOH has the following disadvantages when compared to DNSCrypt:
- Provides more information than regular DNS to resolver operators in order to fingerprint clients, but this is being addressed in the specification
- Requires a full TLS stack and a web server
- Interception/monitoring tools are readily available
- Key management can be surprisingly hard especially if public key pinning is used by clients
- Allows insecure algorithms and parameters
- Requires TCP

To add, DNSCrypt has a very solid Anonymized DNS implementation.

Thanks for the read!

Source: https://dnscrypt.info/faq/

**Comment by jbjorkang** [comment]
Thanks for the comments on this. I will share this with my team.
