### ISSUE TITLE
Missing domains in adblocker

### ISSUE THREAD

**Issue by Y15t** [mullvad/dns-blocklists#76]
Hi,

“googletagmanager.com” does not seem to be blocked when running Mullvad VPN on iOS. Issue for blocking this in apps, since then AdGuard will not do the blocking.

This should be an essential domain to block, but for some reason it is not included in oisd basic.

It’s blocked in the basic filters in AdGuard, DDG & uBlock Origin. 

Probably the easiest fix is to include “Easylist” (easylist.to/easylist/easylist.txt) in your lists. Alternatively The Block List Project ads list (blocklist.GitHub.I’m/Lists/ads.txt) or preferably oisd full (abp.oisd.nl).  

Thanks :)

**Comment by TechD123** [comment]
OISD full would be a great replacement for the OISD basic list currently in use. Perhaps the devs could let us know why they went for basic?

**Comment by hagezi** [comment]
Hi @Y15t

blocking `googletagmanager.com` on DNS level causes some problems on various sites. Videos that do not start, pages that do not load completely and more. This is definitely something for more aggressive DNS lists where you can whitelist yourself. Blocking should be done in a content blocker such as uBlock, as it can also be used for page-specific exclusions.

@TechD123 
OISD does not block `googletagmanager.com`

See: https://github.com/uBlockOrigin/uAssets/search?q=googletagmanager.com&type=issues

Regards,
Gerd - https://github.com/hagezi/dns-blocklists

**Comment by jbjorkang** [comment]
Thanks for your feedback here. We are continuously updating our lists and revisiting the included domains. For now I will close this issue, and if required we can revisit it in future.

We use OISD small currently, this is so we can isolate what is blocked predominantly. The big list and NSFW lists are large, and block more things than we want to in our ad blocking alone.
