### ISSUE TITLE
[Request] Add encrypted support for other list

### ISSUE THREAD

**Issue by BirdInFire** [mullvad/dns-blocklists#83]
Can you add support for all list on DOH:

For how i think of something like:

https://dns.mullvad.net/dns-query -> Unfiltered
https://2.dns.mullvad.net/dns-query -> Ad blocking only
https://3.dns.mullvad.net/dns-query -> Trackers only
https://4.dns.mullvad.net/dns-query -> Ad blocking and tracker blocking
https://5.dns.mullvad.net/dns-query -> Malware blocking only
[ ... ]
 https://31.dns.mullvad.net/dns-query -> Ad blocking, adult content blocking, gambling blocking, malware blocking, tracker blocking ("Everything")

Like that the DOH domain is easy to remember and the number being match with you "vpn dns" settings.

**Comment by jbjorkang** [comment]
Thank you for these suggestions. We are still discussing internally how to handle these combinations.
