### ISSUE TITLE
[Request] Add very limited dns port 53

### ISSUE THREAD

**Issue by BirdInFire** [mullvad/dns-blocklists#84]
Actually like many people i have a router who support dns over tls, but it require an "unencrypted" DNS to "activate" the dns over tls.

It's why i ask you to launch an unencrypted dns BUT unlike the old one you have shut down, this "new" one can ONLY resolve your Encrypted dns domain (so adblock.doh.mullvad.net and doh.mullvad.net).

Like that people like me can use it to activate the secure version and if the modem try to access anything else your unencrypted version will just answer 'REFUSED' or 'NXDOMAIN'

I ask for you do to it because i actually don't trust other DNS and i don't trust my router to not try to ask other thing by the unencrypted version.

**Comment by oskaralmlov** [comment]
I think this is a good suggestion and it's something that I will look into in the near future. Thanks for the suggestion!

**Comment by oskaralmlov** [comment]
This has now been deployed into our production environment, thanks for bringing this to our attention :)

```
oskaralmlov@:~$ dig @doh.mullvad.net doh.mullvad.net adblock.doh.mullvad.net +short
dns.mullvad.net.
194.242.2.2
adblock.dns.mullvad.net.
194.242.2.3
```

Note: `doh/dot.mullvad.net` are now CNAMES to `dns.mullvad.net`, hence the different name in the response.
