### ISSUE TITLE
More variants of blocking

### ISSUE THREAD

**Issue by notDavid** [mullvad/dns-blocklists#87]
Hi there,

so if i read [the docs](https://mullvad.net/en/help/dns-over-https-and-dns-over-tls/#how-to-use) correctly it's only possible to block **Ads** with the public DNS service (using adblock.doh.mullvad.net);

Please consider providing more variants of the IP-addresses/hostnames, like [this](https://github.com/StevenBlack/hosts#list-of-all-hosts-file-variants) for example, to have the ability to also block **Adult, Gambling**, etc.

Reason: i can currently only use this in the Mullvad app, but not on my router...

Thank you!

**Comment by jbjorkang** [comment]
We have plans to bring more parity to our encrypted DNS service soon, thanks for the feedback.

**Comment by jbjorkang** [comment]
> Thank you @jbjorkang
> 
> PS. It would be cool if you would enable "Releases" for this repo, because then people can follow them and will be notified of significant updates/changes, if you write them there :-)

Nice idea! Thanks for the suggestion
