### ISSUE TITLE
Request to add an advertising domain.

### ISSUE THREAD

**Issue by ccnst25** [mullvad/dns-blocklists#88]
(I'm new to GitHub. Please understand if it's awkward.) I found an ad domain that Mullvad DNS couldn't block. Please add the domain to the block list.

Domains : altg.widerplanet.com
The web page on which the ad appears : https://www.chosun.com/
Device info : iOS 16.2, Mozilla Firefox
Screenshots : 
![1](https://user-images.githubusercontent.com/127745297/224688466-08569247-0661-4066-813f-04778ad0af2b.jpg)
![2](https://user-images.githubusercontent.com/127745297/224688562-ede98031-7c9d-4360-b47c-2714cf3c40de.jpg)

**Comment by jbjorkang** [comment]
Thank you for this. It seems like a valid URL to block, but do you know if it is included in a list of URLs to block?

We do not want to curate list of URLs, but rather make use of pre-generated ones.

**Comment by jbjorkang** [comment]
Thanks for this. Could you clarify whether you are using our VPN service?

Just glancing through our lists I can find this is blocked using the DNS block lists on our VPN servers:
```

$ grep -R widerplanet output/
output/relay/relay_privacy.zone:widerplanet.com IN CNAME .
output/relay/relay_adblock.zone:altg.widerplanet.com IN CNAME .
output/relay/relay_adblock.zone:astg.widerplanet.com IN CNAME .
output/relay/relay_adblock.zone:widerplanet.com IN CNAME .
output/relay/relay_adblock.txt:altg.widerplanet.com
output/relay/relay_adblock.txt:astg.widerplanet.com
output/relay/relay_adblock.txt:widerplanet.com
output/relay/relay_privacy.txt:widerplanet.com
output/doh/doh_privacy.txt:widerplanet.com
output/doh/doh_privacy.zone:widerplanet.com IN CNAME .
output/doh/doh_adblock.txt:altg.widerplanet.com
output/doh/doh_adblock.txt:astg.widerplanet.com
output/doh/doh_adblock.txt:widerplanet.com
output/doh/doh_adblock.zone:altg.widerplanet.com IN CNAME .
output/doh/doh_adblock.zone:astg.widerplanet.com IN CNAME .
output/doh/doh_adblock.zone:widerplanet.com IN CNAME .
```

**Comment by ccnst25** [comment]
I was using Mullvad. Now https://www.chosun.com doesn't show that ad. Probably a temporary bug. Thank you for answer.
