### ISSUE TITLE
Use different source for EasyPrivacy domain list

### ISSUE THREAD

**Issue by BartLH** [mullvad/dns-blocklists#90]
The EasyPrivacy list is currently sourced from https://justdomains.github.io/blocklists/lists/easyprivacy-justdomains.txt. This list has not been updated since 3 Oct 2022 (according to https://justdomains.github.io/blocklists/). 

I've opened an issue about this on the justdomains project (https://github.com/justdomains/ci/issues/7) a few weeks ago, this has received no reply. The last commit date is 3 years ago. This leads me to believe the project is dead with a broken CI pipeline.

Mullvad should switch to a different way of obtaining this list. E.g. is there an alternative source, or is it possible to run a (working) copy of the justdomains code locally?

**Comment by oskaralmlov** [comment]
Thanks for making us aware! I'll add this to our todos!

**Comment by jbjorkang** [comment]
Thanks for this, we have switched to use Firebog instead.
