### ISSUE TITLE
add blocklist

### ISSUE THREAD

**Issue by cinatime** [mullvad/dns-blocklists#91]
[hagezi](https://github.com/hagezi/dns-blocklists)  blocklist is a all in one blocklist from multiple sources https://github.com/hagezi/dns-blocklists/blob/main/usedsources.md#ultimate

**Comment by oskaralmlov** [comment]
Thank you for your suggestion!

However it seems like these lists would not be compatible with how our blocking service works. We have categories like ads/tracking/adult etc. and let the customer choose which categories they want to block. These lists seem to mix those categories which wouldn't fit with how it works today. But we'll keep your suggestion in mind for any future reworks of the service.

**Comment by madarie** [comment]
+1 to add hagezi list.Its the best now and well updated.
I think you can contact him so he can split the list according mullvad requirement.
