### ISSUE TITLE
Dandelion Sprout's Anti-Malware Lists

### ISSUE THREAD

**Issue by okpersonvern** [mullvad/dns-blocklists#94]
I would like to suggest adding the Anti-Malware List created and maintained by Dandelion Sprout. It contains many lesser-known but still dangerous malware, scam, and fake shop sites, especially Nordic-language scam sites.
There are some alternate versions of the Anti-Malware List in Dandelion's Github repo that might be compatible with DNS filtering: https://github.com/DandelionSprout/adfilt/tree/master/Alternate%20versions%20Anti-Malware%20List

Wishing you all a splendid and malware-free day!

Cheers.

**Comment by jbjorkang** [comment]
Thank you for this list! I will review and we will add it to be considered.

**Comment by okpersonvern** [comment]
It was decided not to add this?

**Comment by jbjorkang** [comment]
I have added it to our list for the future, unless you think this issue should remain open I feel it adds nothing being here.

**Comment by okpersonvern** [comment]
Not at all, I was just curious. 😊
