### ISSUE TITLE
Dns leak under wifi

### ISSUE THREAD

**Issue by michael1900** [mullvad/dns-blocklists#95]
Hey. Using **adblock.doh.mullvad.net** on my android 13 in Private DNS.

From Mullvad check page:
when i use **home wifi** i have always **dns leak** but ads are blocked w/o problems;
when i use **mobile data connection** i have **NOT dns leak** and also in this case ads are blocked obviously.

Is this normal?

So the only difference is my asus router in a mesh configuration. And the weird thing is that i have the same results using safari on macos and using adblock.doh.mullvad.net in adguard app. 
The question is why under wifi seems to have a dns leak (ads block works, strangely) and instead using mobile connection there aren't dns leak? 

Thanks, i need help!

**Comment by oskaralmlov** [comment]
Which server name is show in the info box on the checkpage where it says DNS is leaking? 

We've recently added some more server to the encrypted dns service (dns/doh.mullvad.net) and it might be that we have forgotten to add one of the new servers to the list of servers that shouldn't be reported as leaking. 

What I'm guesssing is that when you are connected via WIFI your traffic is being routed to what your ISP thinks is the closest server., and that that server hasn't been added to our whitelist. And when you are connected via mobile data your traffic is routed to a server that _is_ added to the whitelist.

The names of the newly added servers and their corresponding IPS are:
```
gb-lon-dns-301.mullvad.net
sg-sin-dns-101.mullvad.net

us-nyc-dns-601.mullvad.net
89.238.154.6
146.70.192.62
193.148.18.30
```

**Comment by michael1900** [comment]
Thanks for reply. 

The dns show in dnsleak when i connected with my home wifi is this: 

<img width="688" alt="Schermata 2023-04-29 alle 14 39 30" src="https://user-images.githubusercontent.com/1675875/235302993-fc57b01c-3ba6-456e-98a3-747329e7bb82.png">

**Comment by oskaralmlov** [comment]
> Thanks for reply. 
> 
> 
> 
> The dns show in dnsleak when i am connected with my home wifi is this: 
> 
> 
> 
> <img width="688" alt="Schermata 2023-04-29 alle 14 39 30" src="https://user-images.githubusercontent.com/1675875/235302993-fc57b01c-3ba6-456e-98a3-747329e7bb82.png">
> 
> 

That is one of the new servers that we've added. You can ignore this for now and it'll be fixed soon. Thanks for reporting this nevertheless.
