### ISSUE TITLE
Ads not being blocked on android

### ISSUE THREAD

**Issue by k4zie** [mullvad/dns-blocklists#96]
I noticed that for the past 4 days, all ads that were previously blocked on websites are now slipping through when using adblock.doh.mullvad.net.

This is on the current version of Android 13.

**Comment by jbjorkang** [comment]
We have verified this internally, and cannot seem to find any issues on our side.

Please reach out to our Support Team regarding this instead by email: support at mullvad dot net

**Comment by k4zie** [comment]
Thank you!
