### ISSUE TITLE
Sebsauvage DNS blocklist

### ISSUE THREAD

**Issue by ghost** [mullvad/dns-blocklists#98]
Hello,

I would like to suggest you a DNS Blocklist.
It's the "Sebsauvage Blocklist DNS" : https://sebsauvage.net/wiki/doku.php?id=dns-blocklist-en

It's a very useful and tiny blocklist which aggregates several blocklists.

Regards,

**Comment by jbjorkang** [comment]
Thanks. I'll be sure to evaluate it
