### ISSUE TITLE
Did you intentionally change the hostnames for your Encrypted DNS?

### ISSUE THREAD

**Issue by rookie-ger** [mullvad/dns-blocklists#99]
In your readme.md you say that the hostnames for your Encrypted DNS are the following:
Vanilla: **dns**.mullvad.net
Ad-block: adblock.**dns**.mullvad.net
Extended: extended.**dns**.mullvad.net

Are you sure it has to be **dns**, not **doh**? The Mullvad [page](https://mullvad.net/en/help/dns-over-https-and-dns-over-tls/) still says **doh**.

**Comment by jbjorkang** [comment]
Thanks for reaching out. The page you are referring to is pending an update, we have a new updated version to be posted soon.

Please consider the dns.mullvad.net variant to be the correct variant.

**Comment by BurhanBudak** [comment]
Maybe off topic but where can I see the DNS service downtime? Its pretty random when I loose internet connection because of the DNS.

**Comment by jbjorkang** [comment]
> Maybe off topic but where can I see the DNS service downtime? Its pretty random when I loose internet connection because of the DNS.

I saw you created a new issue, I will close this one.

**Comment by pointydev** [comment]
@jbjorkang
> Thanks for reaching out. The page you are referring to is pending an update, we have a new updated version to be posted soon.
> 
> Please consider the dns.mullvad.net variant to be the correct variant.

Is there any ETA on the updated version being published? I only just found out that there were 3 new DoH/DoT domains by coming to this repo to look for the relay DNS combination IPs.

**Comment by jbjorkang** [comment]
> @jbjorkang
> > Thanks for reaching out. The page you are referring to is pending an update, we have a new updated version to be posted soon.
> > 
> > Please consider the dns.mullvad.net variant to be the correct variant.
> 
> Is there any ETA on the updated version being published? I only just found out that there were 3 new DoH/DoT domains by coming to this repo to look for the relay DNS combination IPs.

I will check up on the status

**Comment by jbjorkang** [comment]
https://mullvad.net/en/help/dns-over-https-and-dns-over-tls/

This has the updated information
